module.exports = {
  ONLINE: "ONLINE",
  OFFLINE: "OFFLINE",
  AWAY: "AWAY",
  TYPING: "TYPING",
  TYPING_STOPPED: "TYPING_STOPPED",
  ERROR: "ERROR",
  PRIVATE_MESSAGE: "PRIVATE_MESSAGE",
  PRIVATE_CHAT: "PRIVATE_CHAT",
  GROUP_CHAT_ROOM_CREATION: "GROUP_CHAT_ROOM_CREATION",
  GROUP_CHAT_USER_ADDED: "GROUP_CHAT_USER_ADDED",
  GROUP_CHAT_USER_REMOVED: "GROUP_CHAT_USER_REMOVED",
  INITIATE_NEW_SCREEN_SHARE_REQUEST: "INITIATE_NEW_SCREEN_SHARE_REQUEST",
  SCREEN_SHARE_REQUEST_FROM_USER: "SCREEN_SHARE_REQUEST_FROM_USER",
  ACCEPT_SCREEN_SHARE_REQUEST: "ACCEPT_SCREEN_SHARE_REQUEST",
  SCREEN_SHARE_REQUEST_ACCEPTED_BY_USER:
    "SCREEN_SHARE_REQUEST_ACCEPTED_BY_USER",
  REJECT_SCREEN_SHARE_REQUEST: "REJECT_SCREEN_SHARE_REQUEST",
  SCREEN_SHARE_REQUEST_ACCEPTED_BY_USER:
    "SCREEN_SHARE_REQUEST_ACCEPTED_BY_USER",
  SCREEN_SHARE: "SCREEN_SHARE",
  SCREEN_SHARE_END: "SCREEN_SHARE_END"
};
