module.exports = {
  SHOW_CONTACTS: "SHOW_CONTACTS",
  SHOW_SEARCH_RESULTS: "SHOW_SEARCH_RESULTS",
  SHOW_HOME: "SHOW_HOME",
  SHOW_PRIVATE_CHAT_WINDOW: "SHOW_PRIVATE_CHAT_WINDOW",
  SHOW_GROUP_CHAT_WINDOW: "SHOW_GROUP_CHAT_WINDOW",
  NEW_MESSAGE: "NEW_MESSAGE",
  SHOW_OTHER_ACTIVE_CHAT_SESSIONS: "SHOW_OTHER_ACTIVE_CHAT_SESSIONS"
};
