module.exports = {
  HOME_CLICKED: "HOME_CLICKED",
  HEADER_CONTACT_ICON_CLICKED: "HEADER_CONTACT_ICON_CLICKED",
  START_PRIVATE_CHAT_CLICKED: "START_PRIVATE_CHAT_CLICKED",
  START_GROUP_CHAT_CLICKED: "START_GROUP_CHAT_CLICKED",
  SEND_MESSAGE: "SEND_MESSAGE",
  SEARCH_CLICKED: "SEARCH_CLICKED"
};
